## Email Spam Classifier ##

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('spam.csv', encoding='latin-1')
df.sample(5)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
4996,ham,Esplanade lor. Where else...,NaN,NaN,NaN
4643,ham,Did u got that persons story,NaN,NaN,NaN
2332,ham,We are both fine. Thanks,NaN,NaN,NaN
649,spam,"You have won ?1,000 cash or a ?2,000 prize! To...",NaN,NaN,NaN
4704,ham,Hey anyway i have to :-),NaN,NaN,NaN

In [ ]:
df.shape

(5572, 5)

##### 1. Data Cleaning
##### 2. EDA(Exploratory Data Analysis)
##### 3. Text Preprecessing
##### 4. Model Building
##### 5. Evaluation
##### 6. Improvement
##### 7. Website
##### 8. Deploy

# Let's Start

**1. Data Cleaning**

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 217.8 KB

In [ ]:
# drop last 3 column's
df.drop(columns=['Unnamed: 2','Unnamed: 3', 'Unnamed: 4'], inplace=True)

In [ ]:
df.sample

<bound method NDFrame.sample of         v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]>

In [ ]:
# renaming the column's 
df.rename(columns={'v1':'target','v2':'text'}, inplace=True)
df.sample(5)

     target                                               text
2441    ham  Back in brum! Thanks for putting us up and kee...
3915    ham                                      Ok. C u then.
2465    ham                     S.i think he is waste for rr..
5040    ham  She ran off with a younger man. we will make p...
1345    ham    Que pases un buen tiempo or something like that

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder = LabelEncoder()
encoder.fit_transform(df['target'])

NameError: name 'LabelEncoder' is not defined